require: rubocop-rspec

AllCops:
  DefaultFormatter: fuubar
  TargetRubyVersion: 2.3
  DisplayCopNames: true

# default disabled rules
Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    find: 'detect'
    find_all: 'select'

Style/FirstArrayElementLineBreak:
  Enabled: true

Style/FirstHashElementLineBreak:
  Enabled: true

Style/FirstMethodArgumentLineBreak:
  Enabled: true

Style/FirstMethodParameterLineBreak:
  Enabled: true

Style/MultilineArrayBraceLayout:
  Enabled: true

Style/MultilineHashBraceLayout:
  Enabled: true

Style/MultilineMethodCallBraceLayout:
  Enabled: true

Style/MultilineMethodDefinitionBraceLayout:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: true

# non-conventional rules
Style/LambdaCall:
  EnforcedStyle: braces

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

# rules to improve or enable

# Offense count: 5
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Exclude:
    - 'setup.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AlignWith, SupportedStyles.
# SupportedStyles: either, start_of_block, start_of_line
Lint/BlockAlignment:
  Exclude:
    - 'setup.rb'

# Offense count: 1
Lint/DuplicatedKey:
  Exclude:
    - 'setup.rb'

# Offense count: 1
Lint/EmptyWhen:
  Exclude:
    - 'setup.rb'

# Offense count: 2
Lint/HandleExceptions:
  Exclude:
    - 'setup.rb'

# Offense count: 5
Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'setup.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: IgnoreEmptyBlocks, AllowUnusedKeywordArguments.
Lint/UnusedBlockArgument:
  Exclude:
    - 'setup.rb'

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: AllowUnusedKeywordArguments, IgnoreEmptyMethods.
Lint/UnusedMethodArgument:
  Exclude:
    - 'setup.rb'

# Offense count: 1
Metrics/AbcSize:
  Max: 91

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 282

# Offense count: 4
Metrics/CyclomaticComplexity:
  Max: 12

# Offense count: 4
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives.
# URISchemes: http, https
Metrics/LineLength:
  Max: 158

# Offense count: 7
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 99

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 126

# Offense count: 3
Metrics/PerceivedComplexity:
  Max: 12

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
# SupportedStyles: call, braces
Style/LambdaCall:
  EnforcedStyle: call

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Performance/RangeInclude:
  Enabled: false

Lint/UnifiedInteger:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/AlignArray:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 15
